### PR TITLE
add TokenError

### PR DESCRIPTION
**Pull request by lansi951**
If `ErrTokenExpired` occured, want to read previous token and extend expire at.

However, to get previous token in `ErrorHandler`, need to parse one more time in `ErrorHandler`.

Using `ErrorHandlerWithToken`, can get previous token directly without re-parsing.

### CODE REVIEW

**Comment by aldas** [comment]
Hi, maybe more eloquent way would be to introduce new error struct that will hold parsed error and token, has `Unwrap()`, `Error()` etc methods - like fs.PathError does it.

**Comment by lansi951** [comment]
@aldas Hi! Thanks for good review.
I modified commit.

**Comment by aldas** [comment]
This looks OK but needs comments to pass linter. Fix these and you are good to go!

**Comment by lansi951** [comment]
I added comments, but I can't speak english well.
Are comments ok?

**Review by aldas — APPROVED** [review]
LGTM

**Pull request merged**
